# Generated by Django 5.0.6 on 2024-06-08 17:55

from django.db import migrations

from core.constants import CAMPAIGN_TYPES, CHANNELS


def create_campaign_types_and_channels(apps, schema_editor):
    CampaignType = apps.get_model("core", "CampaignType")
    Channel = apps.get_model("core", "Channel")

    for type_code, type_name in CAMPAIGN_TYPES:
        CampaignType.objects.create(name=type_code)

    for channel_code, channel_name in CHANNELS:
        Channel.objects.create(name=channel_code)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_campaign_types_and_channels),
    ]
