version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: marketing_op_db
      POSTGRES_USER: op_candidate
      POSTGRES_PASSWORD: op_strong_password
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  marketing_op:
    build: .
    image: marketing_op_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./marketing_op/:/usr/objective_platform/marketing_op/
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./start_server.sh'

volumes:
    db_data: